export default function GlossarySection({ active }) {
  const terms = [
    {
      term: "ADB — Average Daily Balance",
      def: "Time-weighted mean of a merchant's daily closing bank balance. The primary liquidity metric used in lender attribute scoring.",
    },
    {
      term: "Attribute Score (Layer C)",
      def: "Rule-based component of the composite score. Measures merchant risk profile against lender buy-box criteria. Weight: 25%.",
    },
    {
      term: "Buy-Box",
      def: "A lender's published underwriting criteria: minimum revenue, minimum FICO, maximum positions, restricted industries and states.",
    },
    {
      term: "Composite Score",
      def: "The 0–100 output of the three-layer scoring model for a specific merchant-lender pairing. Reflects both market signals and your ISO's relationship history.",
    },
    {
      term: "Digital Head of Submissions",
      def: "YieldStream's positioning concept. The platform functions as an institutional-grade submissions function, replacing ad hoc lender routing with systematic, data-driven recommendations.",
    },
    {
      term: "Global Pool (Layer A)",
      def: "Cross-organization, anonymized lender performance signal. Computes time-decay weighted approval rates across all YieldStream ISOs without exposing any individual ISO's data. Weight: 25%.",
    },
    {
      term: "Ghosting Rate",
      def: "Ratio of submissions with no lender response within the expected window to total submissions, over a rolling 30-day period.",
    },
    {
      term: "ISO — Independent Sales Organization",
      def: "The primary YieldStream customer. An ISO is a licensed MCA broker organization that matches merchants with MCA lenders and earns commission on funded deals.",
    },
    {
      term: "MCA — Merchant Cash Advance",
      def: "A form of small business financing where a lender purchases a portion of future receivables at a discount, repaid via daily or weekly fixed debits.",
    },
    {
      term: "NSF — Non-Sufficient Funds",
      def: "A bank event indicating a payment was attempted with an insufficient balance. The strongest single negative signal in MCA underwriting.",
    },
    {
      term: "Outcome Learning Loop",
      def: "The feedback mechanism feeding every funded and declined deal back into the scoring model. The primary driver of model improvement over time.",
    },
    {
      term: "Pull-Through Rate",
      def: "Funded deals ÷ total deals submitted to a specific lender. An ISO's most important metric of lender relationship quality.",
    },
    {
      term: "Relationship Score (Layer B)",
      def: "ISO-specific, time-decay weighted pull-through history with each lender. Weight: 50%. Never shared with competing ISOs.",
    },
    {
      term: "Stacking",
      def: "Having multiple simultaneous MCA advances from different lenders. Detected from bank statement debit patterns and expressed as stacking_burden_pct.",
    },
    {
      term: "Time-Decay Weighting",
      def: "Mechanism that reduces the influence of older outcomes on current scores. Data older than 180 days contributes only 5% weight, preventing stale signals from distorting recommendations.",
    },
    {
      term: "Underwriter's Note",
      def: "A human-readable sentence generated by Gemini 1.5 Flash explaining the structural reason for a lender recommendation. Provides broker-facing transparency for AI-driven scores.",
    },
  ];

  return (
    <section
      className={`docs-section ${active ? "vis" : ""}`}
      id="sec-glossary"
    >
      <div className="docs-pg-lbl">Reference</div>
      <div className="docs-h1">Glossary</div>
      <div className="docs-lead">
        Definitions for YieldStream-specific terminology used throughout
        this documentation and visible in the platform interface.
      </div>

      {terms.map((item) => (
        <div className="docs-glos-item" key={item.term}>
          <div className="docs-glos-term">{item.term}</div>
          <div className="docs-glos-def">{item.def}</div>
        </div>
      ))}
    </section>
  );
}
